spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sakila}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

app:
  docs:
    public: true

logging:
  level:
    org.hibernate.SQL: debug
